# Generated by Django 3.0.4 on 2020-04-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.TextField(verbose_name='Title')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('runTime', models.IntegerField(verbose_name='Run Time')),
                ('categories', models.TextField(verbose_name='Categories')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('poster', models.TextField(verbose_name='Poster URL')),
            ],
        ),
    ]
