# Generated by Django 3.0.4 on 2020-04-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.TextField(null=True, verbose_name='Poster URL'),
        ),
    ]
