# Generated by Django 3.0.4 on 2020-04-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200419_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.TextField(blank=True, default='', verbose_name='Poster URL'),
            preserve_default=False,
        ),
    ]
